# .github/workflows/main.yml

name: Build and deploy Python app to Azure Web App - EliteDynamicsAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: elitedynamicsapi
  PYTHON_VERSION: '3.11'
  PACKAGE_PATH: '.' # Indica que la aplicación está en la raíz del repositorio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # EL PASO DE CREACIÓN DEL ZIP HA SIDO ELIMINADO

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.PACKAGE_PATH }} # <-- SE HA CAMBIADO PARA APUNTAR AL CÓDIGO FUENTE